<a href="https://colab.research.google.com/github/K9Patel/K9Patel/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Basics Python

SyntaxError: invalid syntax (ipython-input-2830201818.py, line 1)

In [8]:
import numpy as np


In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [9]:
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2,2)

array([[0.51305548, 0.59046961],
       [0.43949064, 0.87049401]])

In [1]:
np.random.randint(0,101)

NameError: name 'np' is not defined

In [6]:
np.random.randint(0,101,5)

array([48, 22,  1, 71, 86])

In [5]:
np.random.randint(0,101,(4,5))

array([[49, 71, 63,  9, 22],
       [70, 12, 93, 46, 50],
       [92, 94, 50, 11, 49],
       [27, 98, 42, 39, 20]])

In [7]:
git init

SyntaxError: invalid syntax (ipython-input-2830201818.py, line 1)

In [12]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [14]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
r = np.random.randint(0,101,10)
r

array([57, 21, 88, 48, 90, 58, 41, 91, 59, 79])

In [20]:
print(r.max())
print(r.min())
print(r.argmax())
print(r.argmin())
print(r.dtype)

91
21
7
1
int64


In [22]:
arrr=np.arange(0,40)

In [23]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [25]:
arrr[0:4]

array([0, 1, 2, 3])

In [26]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arrr[0:10]=100

In [29]:
arrr


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

In [34]:
slice=arrr[0:5]

In [35]:
slice

array([100, 100, 100, 100, 100])

In [36]:
slice[:]=99

In [37]:
slice

array([99, 99, 99, 99, 99])

In [38]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
a_c=arrr.copy()

In [42]:
a_c[:5]=800

In [44]:
a_c

array([800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800,
       800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800,
       800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800,
       800])

In [45]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr_2d.shape

(3, 3)

In [49]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [50]:
arr=np.arange(0,14)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [53]:
b=arr > 10

In [55]:
arr[b]

array([11, 12, 13])

In [56]:
arr[arr>6]

array([ 7,  8,  9, 10, 11, 12, 13])

In [57]:
arr = np.arange(0,10)

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr -3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [61]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [63]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.mean(arr) )
print(np.max(arr) )
print(np.var(arr) )
print(np.std(arr) )

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
4.5
9
8.25
2.8722813232690143


/tmp/ipython-input-1949189423.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [68]:
arr2d = np.arange(0,25).reshape(5,5)

In [69]:
arr2d.sum()

np.int64(300)

In [71]:
 arr2d.sum(axis=0)   #column

array([50, 55, 60, 65, 70])

In [72]:
arr2d.sum(axis=1)   #row

array([ 10,  35,  60,  85, 110])